package sebastian.devmonkey.capstoneproject.other;

public class Arrays {

    private String[] poemTitles = {
            "Sonnet 1",
            "Sonnet 2",
            "Sonnet 3",
            "Sonnet 4",
            "Sonnet 5",
            "Sonnet 6",
            "Sonnet 7",
            "Sonnet 8",
            "Sonnet 9",
            "Sonnet 10",
            "Sonnet 11",
            "Sonnet 12",
            "Sonnet 13",
            "Sonnet 14",
            "Sonnet 15",
            "Sonnet 16",
            "Sonnet 17",
            "Sonnet 18",
            "Sonnet 19",
            "Sonnet 20",
            "Sonnet 21",
            "Sonnet 22",
            "Sonnet 23",
            "Sonnet 24",
            "Sonnet 25",
            "Sonnet 26",
            "Sonnet 27",
            "Sonnet 28",
            "Sonnet 29",
            "Sonnet 30",
            "Sonnet 31",
            "Sonnet 32",
            "Sonnet 33",
            "Sonnet 34",
            "Sonnet 35",
            "Sonnet 36",
            "Sonnet 37",
            "Sonnet 38",
            "Sonnet 39",
            "Sonnet 40",
            "Sonnet 41",
            "Sonnet 42",
            "Sonnet 43",
            "Sonnet 44",
            "Sonnet 45",
            "Sonnet 46",
            "Sonnet 47",
            "Sonnet 48",
            "Sonnet 49",
            "Sonnet 50",
            "Sonnet 51",
            "Sonnet 52"
    };

    private String[] storyTitles = {"500 MILES RACE",
            "A CALL TO THE POOL",
            "A HAPPY VISITOR.",
            "AIR BALLOON",
            "AIRPLANES",
            "ALLIGATORS",
            "BEARS",
            "BEDS",
            "BELLA HIDES",
            "BIG CITY NOISE",
            "BIRDS",
            "BIRD'S NEST",
            "BULLIED",
            "BUTTERFLY",
            "BY THE WATER",
            "CAMPFIRE",
            "CANNED GOODS",
            "DANDELIONS",
            "DIFFERENT TYPES OF PEOPLE",
            "DOGS",
            "EMPRESS OF THE BLUES",
            "FISH",
            "FLAGS",
            "FRIED",
            "GRASS",
            "GREEN GRASS",
            "GRIFIN",
            "GRIFIN'S TALENT",
            "HELICOPTERS",
            "HOUSES",
            "HOW ARE YOU",
            "HOW SEEDS GROW",
            "HOW WARTHOG LIVES",
            "HOW WORMS GET INSIDE AN APPLE",
            "HUMANS",
            "I FLY",
            "ICE FISHING",
            "JULIAN",
            "JUPITER",
            "LAND OF AFRICA",
            "LEONARDO DA VINCI",
            "LORD OF OLYMPUS",
            "MONEY",
            "MY FAMILY",
            "MY FRIEND",
            "MY HOUSE",
            "NEW SHOES FOR MADDY",
            "ONE HUNDRED DOLLARS",
            "PAPER",
            "PARTS OF A PIANO",
            "PAUL COOKS",
            "RAINY DAY",
            "RUNNING",
            "SEEING STARS",
            "SKY",
            "SOAP",
            "SODA POP",
            "STORY OF LORD SANDWICH",
            "TALIA",
            "TASTE",
            "TEA",
            "TELEVISIONS",
            "TENNIS",
            "THE 20",
            "THE BLOW DRYER",
            "THE CAT , THE ROOSTER AND THE YOUNG MOUSE WRITER",
            "THE DOG AND HIS REFLECTION",
            "THE DOG AND THE MANGER",
            "THE DONKEY IN THE LION'S SKIN",
            "THE DRIVE",
            "THE FOG AND THE FOX",
            "THE FOX AND THE CROW",
            "THE FOX AND THE GRAPES",
            "THE HAWAIIAN PEOPLE SONG",
            "THE HEART",
            "THE INTERVIEW",
            "THE LION AND THE MOUSE",
            "THE MICE IN COUNCIL",
            "THE MUSIC",
            "THE RABBIT AND THE TURTLE",
            "THE RED CARPET TREATMENT",
            "THE RENT MAN",
            "THE ROOSTER AND THE FOX",
            "THE ROOSTER AND THE JEWEL",
            "THE SINGING BIRD",
            "THE SKY",
            "THE TREES AND THE AX",
            "THE UNITED STATES",
            "THE WIND AND THE SUN",
            "TIE YOUR SHOES",
            "TIME TO",
            "TREES",
            "WHAT NUMBER",
            "WHAT TIME IS IT",
            "WHERE ARE MY GLASSES",
            "YELLOWSTONE NATIONAL PARK",
            "ZACH"


     };

    private String[] storyIntermediateTitle = {
            "A COLD DAY",
            "A MYSTERY",
            "ABRAHAM LINCOLN",
            "AMAZON RAINFOREST",
            "AMERICAN INDIAN NAMES",
            "AMERICA'S FIRST SCUPTOR",
            "AMERICA'S FIRST WOMAN",
            "ARTIC FOX",
            "BAIL",
            "BANKS",
            "BENJAMIN FRANKLIN",
            "BIRD SONGS",
            "BLACK AMERICAN AUTHOR",
            "BLACK BEARS",
            "BLIZZARD UN BIRMINGHA",
            "BLUE WHALE",
            "BUTTERFLIES",
            "CARS",
            "CHRISTOPHER COLUMBUS",
            "CITY NOISE",
            "CLOCKS",
            "COINS",
            "COMMON LOON",
            "CORN",
            "COUNTING",
            "CRICKET",
            "DISCOVERY OF ICE CREAM",
            "DOCTOR IN CHICAGO",
            "DUNKIN DONUTS",
            "EASTER ISLAND",
            "GARLICS",
            "HALLOWEEN",
            "HELICOPTERS",
            "HIBERNATION AND ESTIVATION",
            "HOUSES",
            "HOW TO BE A PIG",
            "JOHN COOKS",
            "KOMODO DRAGON",
            "LARGEST CREATURE ON EARTH",
            "LATE",
            "LOBSTER",
            "LOCKS AND KEYS",
            "MARCO POLO",
            "MARS",
            "MARYS FAMILY",
            "MOORISH DANCE",
            "MOVIE RATINGS",
            "MUMMY",
            "NIAGARA FALLS",
            "NUTS",
            "OLYMPIC GAME",
            "PANDA",
            "PENQUINS"
    };
    private String[] storyHardTitle = {
            "A CHRISTMAS IN MARCH",
            "A DARING ESCAPE",
            "ACCUSED",
            "ADVANCE CRITICAL READING",
            "ANA FINDS AN",
            "ASIAN CARP",
            "BATHTUBS",
            "BB",
            "BLACK FRIDAY",
            "CAN WINDMILLS STALK",
            "CANOPY OF NATURE",
            "CARNIVOROUS",
            "CELLS",
            "CHOCOLATE",
            "CITY GIRL",
            "CLEAN WATER ACT",
            "COLLECTION OF FOLKLORE",
            "DREAMS",
            "EATING OUT",
            "EL DIA DE SAN JUAN",
            "EUROPE",
            "FINGERPRINTS",
            "FLORIDA_MANATEE",
            "FLOWER POWER",
            "FORTUNE TELLERS",
            "FRANCE",
            "GALAXIES",
            "GILRAY'S FLOWER POT",
            "GOODLUCK FOR THE GOOD",
            "GUERMO'S SURPRISE",
            "HOUSE AROUND THE WORLD",
            "INTERSTATE HIGHWAY",
            "JUAN PONCE",
            "JUST ONE TOUCH",
            "KOK",
            "LIGHTNING AND THUNDER",
            "LOVE TRAIN",
            "MARIA'S BEAUTIFUL",
            "METEORS",
            "MEXICO",
            "MOONGOOES",
            "MOSQUITOES",
            "MOTHER'S DAY",
            "OIL SPILL",
            "ON THE RIGHT TRACK",
            "OVERSMART IS BAD LUCK",
            "PLANET MARS",
            "POLUTTIONS",
            "POTATO CHIPS",
            "RAISINGS",
            "ROUND AND ROUND",
            "SEAT BELTS",
            "SEEING CLEARLY",
            "SHARKS",
            "SLEEP",
            "SUFFRAGE",
            "TAKE CARE OF YOUR DOG",
            "TARO AND THE TOFU",
            "TATTOO",
            "THE CASE OF THE UNKNOWN",
            "THE CAT THAT WALKED",
            "THE CLEVER WIZARD",
            "THE COLISEUM",
            "THE COWARDLY LION",
            "THE FIRST WORDS",
            "THE GREAT BUDDHA",
            "THE MINI PROBLEM",
            "THE SECRET SOLDIER",
            "THE SON",
            "THE STORM",
            "THE STORY OF KEESH",
            "THE TRANSFER",
            "TRACKS",
            "TYRANNUSIRUS REX",
            "VENUS",
            "WAMPUM",
            "WHAT A PIG-TURE",
            "WILD"

    };

    private String[] terminologiesWords = {
            "Spurious",
            "Gossip",
            "Fraternizing",
            "Vicariously",
            "Brazen",
            "Coveted",
            "Deficit",
            "Copious",
            "Augmentation",
            "Evoke"
    };

    private String[] terminologiesMeaning = {
            "not being what it purports to be; false or fake.",
            "casual or unconstrained conversation or reports about other people, typically involving details that are not confirmed as being true.",
            "associate or form a friendship with someone, especially when one is not supposed to.",
            "in a way that is experienced in the imagination through the actions of another person.",
            "endure an embarrassing or difficult situation by behaving with apparent confidence and lack of shame.",
            "yearn to possess or have (something).",
            "the amount by which something, especially a sum of money, is too small.",
            "abundant in supply or quantity.",
            "the action or process of making or becoming greater in size or amount.",
            "bring or recall to the conscious mind."
    };




    public String[] getStoryTitles() {
        return storyTitles.clone();
    }
    public String[] getStoryIntermediateTitleTitles() {
        return storyIntermediateTitle.clone();
    }
    public String[] getStoryHardTitles(){return  storyHardTitle.clone();}



    public String[] getTerminologiesWords() {
        return terminologiesWords.clone();
    }

    public String getTerminologiesWords1(int a) {
        return terminologiesWords[a];
    }
    public String getTerminologiesMeaning(int a) {
        return terminologiesMeaning[a];
    }

    public String[] getPoemTitles() {
        return poemTitles.clone();
    }




//    public int getLength() {
//        return mQuestion.length;
//    }


}
